version: '3'

services:
  php:
    container_name: tca-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tca-network

  nginx:
    container_name: tca-nginx
    image: nginx:1.23
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tca-network

  mysql:
    container_name: tca-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    tty: true
    volumes:
      - tca-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - tca-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: tca
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

networks:
  tca-network:
    driver: bridge

volumes:
  tca-data:
    driver: local